#!/bin/sh
csv=$1
matlab -nodesktop -nosplash <<EOF
clear;
addpath(genpath('.'));
InitBreach;

u_ts=0.001;
mdl = 'narmamaglev_v1';
Br = BreachSimulinkSystem(mdl);
Br.Sys.tspan =0:.01:20;
input_gen.type = 'UniStep';
input_gen.cp = 3;
Br.SetInputGen(input_gen);
for cpi = 0:input_gen.cp -1
	Ref_sig = strcat('Ref_u',num2str(cpi));
	Br.SetParamRanges({Ref_sig},[1.0 3.0]);
end
spec = 'alw_[0, 18]((not (abs(Pos[t] - Ref[t]) <= 0.001+ 0.04*abs(Ref[t])))=> ev_[0, 2] (alw_[0, 1] (abs(Pos[t] - Ref[t]) <= 0.001+ 0.04*abs(Ref[t]))))';
phi = STL_Formula('phi',spec);
trials = 1;
filename = 'narmamaglev_v1_breach_NN1_1_3_cmaes';
algorithm = 'Breach';
falsified = [];
time = [];
obj_best = [];
num_sim = [];
for n = 1:trials
	falsif_pb = FalsificationProblem(Br,phi);
	falsif_pb.max_time = 600;
	falsif_pb.setup_solver('cmaes');
	falsif_pb.solve();
	if falsif_pb.obj_best < 0
		falsified = [falsified;1];
	else
		falsified = [falsified;0];
	end
	num_sim = [num_sim;falsif_pb.nb_obj_eval];
	time = [time;falsif_pb.time_spent];
	obj_best = [obj_best;falsif_pb.obj_best];
end
spec = {spec};
filename = {filename};
result = table(filename, spec, falsified, time,  obj_best, num_sim);
writetable(result,'$csv','Delimiter',';');
quit
EOF
